import "../globals.css";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";

export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function ActivityLayout({ children }) {
  return <>{children}</>;
}
